name: package
on:
  workflow_dispatch:
    inputs:
      chosen-os:
        required: true
        type: choice
        options:
          - Ubuntu
          - macos-latest
          - ubuntu-latest
          - ubuntu-20.04
          - ubuntu-22.04

jobs:
  package-ubuntu:
    if: github.repository_owner == 'HATTER-LONG'
    runs-on: [self-hosted, "${{ inputs.chosen-os }}"]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required to count the commits
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
      - name: Run lockfile-autoupdate
        timeout-minutes: 5
        run: |
          ./scripts/install.sh
          nvim --headless "+Lazy! update" +qa
          rm -rf ${HOME}/.config/nvim/.git
          tar -cvzf nvimdots.tar.gz ${HOME}/.config/nvim/
      - uses: actions/upload-artifact@v1
        with:
          name: package
          path: ./nvimdots.tar.gz
