name: package
on:
  workflow_dispatch:
    inputs:
      chosen-os:
        required: true
        type: choice
        options:
          - ubuntu-22.04
          - ubuntu-20.04
          - macos-latest
          - ubuntu-latest

jobs:
  package-ubuntu:
    if: github.repository_owner == 'HATTER-LONG'
    runs-on: ["${{ inputs.chosen-os }}"]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required to count the commits
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
      - name: Run lockfile-autoupdate
        timeout-minutes: 5
        run: |
          export GITHUB_ACTION=TRUE
          ./scripts/install.sh
          nvim --headless "+Lazy! update" +qa
          nvim --headless "+MasonInstall bash-language-server clangd json-lsp lua-language-server python-lsp-server" +qa
          rm -rf ${HOME}/.config/nvim/.git
      - uses: actions/upload-artifact@v3
        with:
          name: nvimdots
          path: ~/.config/nvim*
